config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'boards#index'
  resources :boards do
    resources :tasks
  end

  namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
      resources :boards, only: %i() do
        resources :tasks, only: %i() do
          resources :comments, only: %i(index create destroy), shallow: true
        end
      end
      resources :tasks, only: %i() do
        resource :status, only: %i(update), module: :tasks
      end
    end
  end
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :text
#  due_date    :date
#  name        :string           not null
#  status      :integer          default("todo"), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (user_id => users.id)
#
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_many :comments, dependent: :destroy
  has_many :successor_dependencies, foreign_key: 'predecessor_id', class_name: 'TaskDependency', dependent: :destroy
  has_many :successors, through: :successor_dependencies, source: :successor
  has_many :predecessor_dependencies, foreign_key: 'successor_id', class_name: 'TaskDependency', dependent: :destroy
  has_many :predecessors, through: :predecessor_dependencies, source: :predecessor
  has_one_attached :thumbnail

  enum status: { todo: 0, done: 1 }

  validates :name, presence: true

  #successorsを持つ場合、既存のpredecessorのみ選択可
  def selectable_predecessors
    scope = board.tasks.where.not(id: id)
    return scope unless successors.exists?
    predecessors.merge(scope)
  end

  def comments_count
    self.comments.count
  end

  def comment_users
    User.where(id: comments.select(:user_id).distinct)
  end

  def has_predecessors_todo?
    if predecessors.loaded?
      predecessors.any?(&:todo?)
    else
      predecessors.where(status: :todo).exists?
    end
  end

  def pending?
    todo? && has_predecessors_todo?
  end

  def display_status
    return 'done' if done?
    return 'pending' if pending?
    status
  end

  def predecessor?
    successor_dependencies.exists?
  end
end

app/views/commons/_board-card.html.haml
.px-3.py-3.rounded-lg.shadow-md.bg-brandGrayLight.relative.md:px-5.md:py-5{ data: { id: board.id } }
  = link_to '', board_path(board), class: 'absolute inset-0' if local_assigns.fetch(:show_read_more, true)
  .flex.items-center.justify-between.gap-3
    %p.text-xl.font-bold.text-brandBlack= board.name
    - if user_signed_in? && board.user == current_user
      = render 'commons/dropdown_actions',
               edit_path: edit_board_path(board),
               delete_path: board_path(board)
  %p.mt-1.text-brandGrayDark= board.description
  .flex.gap-2.items-center.justify-between.mt-6
    .flex.items-center.gap-2
      = image_tag board.user.avatar_image, class: 'flex-shrink-0 size-8 rounded-full'
      %p.font-bold.text-brandBlack= board.user.name

app/views/commons/_board-form.html.haml
= form_with(model: board, local: true, data: { turbo: false }) do |f|
  .w-full.mt-4
    %label.label{ for: 'board_name' }
      Name
    = f.text_field :name, class: 'input'
  .w-full.mt-4
    %label.label{ for: 'board_description' }
      Description
    = f.text_area :description, class: 'input'
  .flex.items-center.justify-center.mt-4
    = f.submit 'Submit', class: 'submit'

app/views/commons/_comment-form.html.haml
%form.comment-form.space-y-2#js-comment-form
  = text_area_tag :comment_content, '', class: 'input', placeholder: 'コメントを投稿', required: true
  %button.submit.w-full.py-2 Submit

app/views/commons/_dropdown_actions.html.haml
- edit_path = local_assigns.fetch(:edit_path)
- delete_path = local_assigns.fetch(:delete_path)

%button{ class: 'cursor-pointer p-2 relative hover:[&>*]:opacity-100 hover:[&>*]:visible focus-within:[&>*]:opacity-100 focus-within:[&>*]:visible' }
  %span.text-2xl …
  .absolute.top-full.right-0.z-10.w-30.bg-white.rounded-md.shadow-xl.opacity-0.invisible.transition-opacity.delay-100.w-fit.border.border-brandGrayLight
    = link_to edit_path do
      .menu-width-icon
        = image_tag 'icon_write.svg', class: 'w-5 h-5 mx-1'
        %span.mx-1
          Edit
    = link_to delete_path, data: { turbo_confirm: 'この操作は取り消せません。本当に削除しますか？', turbo_method: 'delete' } do
      .menu-width-icon
        = image_tag 'icon_delete.svg', class: 'w-5 h-5 mx-1 flex-shrink-0'
        %p.mx-1.flex-1
          Delete

app/views/commons/_flash.html.haml
:ruby
  key = local_assigns.fetch(:key, nil).to_s.presence || 'notice'
  message = local_assigns.fetch(:message, nil).presence
  return if message.blank?

%div{ :class => "w-full text-white fade-out js-flash #{flash_accent_class(key)}" }
  .container.flex.items-center.justify-between.px-4.py-4.mx-auto
    .flex.items-center
      %svg.w-6.h-6.fill-current.flex-shrink-0{ :viewbox => '0 0 40 40' }
        %path{ :d => 'M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM21.6667 28.3333H18.3334V25H21.6667V28.3333ZM21.6667 21.6666H18.3334V11.6666H21.6667V21.6666Z' }
      %p.mx-2.text-sm= message
    %button.p-1.transition-colors.duration-300.transform.rounded-md.cursor-pointer.js-flash-close-button
      %svg.w-5.h-5{ :fill => 'none', :viewbox => '0 0 24 24', :xmlns => 'http://www.w3.org/2000/svg' }
        %path{ :d => 'M6 18L18 6M6 6L18 18', :stroke => 'currentColor', 'stroke-linecap' => 'round', 'stroke-linejoin' => 'round', 'stroke-width' => '2' }

app/views/commons/_form_errors.html.haml
- object = local_assigns[:object]
- if object&.respond_to?(:errors) && object.errors.any?
  .bg-brandGrayLight.border.border-danger.text-danger.px-4.py-3.rounded.my-4
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/commons/_task-card.html.haml
.relative.rounded-lg.shadow-md.border.border-brandGray.flex.flex-col.gap-3.bg-white
  = link_to '', board_task_path(board.id, task.id), class: 'inset-0 absolute'
  .px-3.py-3.md:px-5.md:py-5
    .flex.items-center
      .space-y-2
        .task-status{ data: { status: task.display_status } }= task.display_status
        %p.text-xl.font-bold.text-brandBlack= task.name
      - if user_signed_in? && task.user == current_user
        .ml-auto
          = render 'commons/dropdown_actions',
                   edit_path: edit_board_task_path(board, task),
                   delete_path: board_task_path(board, task)
    .flex.items-center.gap-1.justify-between.mt-4
      = image_tag task.user.avatar_image, class: 'shrink-0 size-8 rounded-full'
      .flex.items-center.gap-2
        .flex.items-center.gap-1.shrink-0
          - task.comment_users.each do |user|
            = image_tag user.avatar_image, class: 'shrink-0 size-6 rounded-full'
        .flex.items-center.gap-1.shrink-0
          = image_tag 'icon_comment.svg', class: 'shrink-0 size-5'
          = task.comments_count

app/views/commons/_task-form.html.haml
= form_with(model: [board, task], local: true, data: { turbo: false }) do |f|
  .w-full.mt-4
    %label.label{ for: 'task_thumbnail' }
      Thumbnail
    = f.file_field :thumbnail, class: 'input-file'
  .w-full.mt-4
    %label.label{ for: 'task_name' }
      Name
    = f.text_field :name, class: 'input'
  .w-full.mt-4
    %label.label{ for: 'task_description' }
      Description
    = f.text_area :description, class: 'input'
  .w-full.mt-4
    %label.label{ for: 'task_due_date' }
      Due Date
    = f.date_field :due_date, class: 'input'
  - unless task.new_record?
    - if task.selectable_predecessors.any?
      .w-full.mt-4
        %label.label{ for: 'task_predecessor_ids' }
          Dependencies
        .mt-2.input.space-y-1
          = f.collection_check_boxes :predecessor_ids, task.selectable_predecessors, :id, :name do |b|
            .flex.items-center
              = b.check_box(class: 'mr-1')
              = b.label(class: 'cursor-pointer')
  .flex.items-center.justify-center.mt-4
    = f.submit 'Save', class: 'submit'

app/views/commons/_user-menu.html.haml
%button.cursor-pointer.relative.flex.items-center.p-2.text-sm.border.border-brandGrayLight.bg-white.rounded-md{ class: 'hover:[&>*]:opacity-100 hover:[&>*]:visible focus-within:[&>*]:opacity-100 focus-within:[&>*]:visible' }
  = image_tag 'icon_profile.svg', class: 'w-5 h-5 mx-1'
  %span.mx-1= current_user.name
  .absolute.top-full.right-0.z-20.w-fit.py-2.overflow-hidden.origin-top-right.bg-white.rounded-md.shadow-xl.opacity-0.invisible.transition-opacity.delay-100
    .flex.items-center.p-3.-mt-2.gap-2.text-sm.transition-colors.duration-300
      = image_tag current_user.avatar_image, class: 'flex-shrink-0 rounded-full size-8'
      .mx-1
        %p.text-left.text-sm.font-semibold.text-brandBlack= current_user.name
        %p.text-sm= current_user.email
    %hr.border-brandGrayLight
    = link_to edit_user_registration_path do
      .menu-width-icon
        = image_tag 'icon_profile.svg', class: 'w-5 h-5 mx-1'
        %span.mx-1
          Edit Profile
    = link_to destroy_user_session_path, data: { turbo_confirm: 'ログアウトしますか？', turbo_method: 'delete' } do
      .menu-width-icon
        = image_tag 'icon_sign-out.svg', class: 'w-5 h-5 mx-1'
        %span.mx-1
          Log Out
    %hr.border-brandGrayLight
    = link_to registration_path(current_user), data: { turbo_confirm: '本当に削除しますか?', turbo_method: :delete } do
      .menu-width-icon
        = image_tag 'icon_delete.svg', class: 'w-5 h-5 mx-1'
        %span.mx-1
          Delete account