config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'boards#index'
  resources :boards do
    resources :tasks
  end

  namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
      resources :boards, only: %i() do
        resources :tasks, only: %i() do
          resources :comments, only: %i(index create destroy), shallow: true
        end
      end
      resources :tasks, only: %i() do
        resource :status, only: %i(update), module: :tasks
      end
    end
  end
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true

  def done_tasks_count
    tasks.where(status: 'done').count
  end

  def tasks_count
    tasks.count
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_board, only: [:edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)

    if @board.save
      redirect_to board_path(@board), notice: 'ボードが作成されました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks.includes(:predecessors).order(created_at: :asc)
    @done_tasks, todo_tasks = @tasks.partition(&:done?)
    @todo_tasks, @pending_tasks = todo_tasks.partition { |task| !task.pending? }
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), notice: 'ボードが更新されました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board.destroy!
    flash[:success] = '削除しました。'
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :description)
  end

  def set_board
    @board = current_user.boards.find(params[:id])
  end
end

app/views/boards/edit.html.haml
.w-full.max-w-sm.mx-auto.overflow-hidden.bg-white.rounded-lg.shadow-md
  .px-6.py-6
    %h2.mt-3.text-xl.font-medium.text-center.text-brandGrayDark Edit Board
    = render 'commons/form_errors', object: @board
    = render 'commons/board-form', board: @board

app/views/boards/index.html.haml
.grid.grid-cols-1.gap-6.p-4.bg-white.shadow-lg.rounded.md:p-6.md:grid-cols-2
  = link_to '＋ Add new board', new_board_path, class: 'new-card'
  - @boards.reverse.each do |board|
    = render 'commons/board-card', board: board

app/views/boards/new.html.haml
.w-full.max-w-sm.mx-auto.overflow-hidden.bg-white.rounded-lg.shadow-md
  .px-6.py-6
    %h2.mt-3.text-xl.font-medium.text-center.text-brandGrayDark New Board
    = render 'commons/form_errors', object: @board
    = render 'commons/board-form', board: @board

app/views/boards/show.html.haml
.bg-white.shadow-lg.rounded-lg.max-w-2xl.p-3.rounded-lg.mx-auto.md:p-6{ data: { id: @board.id } }
  .space-y-1
    .task-status{ data: { status: 'done' } }
      ⚪︎ #{@board.done_tasks_count} / #{@board.tasks_count}
    .font-bold.text-2xl= @board.name
    .mt-1.text-brandGrayDark.text-lg= @board.description
  .mt-8.space-y-4
    %h2.text-2xl.font-bold.bg-brandGrayLight.p-2.rounded
      %span.text-green-600 ●
      %span TODO
    - @todo_tasks.each do |task|
      = render 'commons/task-card', board: @board, task: task, show_read_more: false
    = link_to '＋ Add new Task', new_board_task_path(@board.id), class: 'new-card'
  - if @pending_tasks.any?
    .mt-8.space-y-4
      %h2.text-2xl.font-bold.bg-brandGrayLight.p-2.rounded
        %span.text-gray-500 ●
        %span PENDING
      - @pending_tasks.each do |task|
        = render 'commons/task-card', board: @board, task: task, show_read_more: false
  - if @done_tasks.any?
    .mt-8.space-y-4
      %h2.text-2xl.font-bold.bg-brandGrayLight.p-2.rounded
        %span.text-purple-600 ●
        %span DONE
      - @done_tasks.each do |task|
        = render 'commons/task-card', board: @board, task: task, show_read_more: false